name: Workflows_by_Job
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  venv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Venv Activation
        run: |
          make venv
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          make install
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: |
          make format
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pylint
        run: |
          make pylint
  unitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit Tests
        run: |
          make test